Repository Roll20/roll20-character-sheets, pull requests merged in 2022-10, with the labels that each got.

#11098 [Ironsworn] Fix missing oracle translations
  Ironsworn/Ironsworn.html
  Ironsworn/translation.json
Labels: being reviewed

#11058 New CharacterSheet for Tormenta20 - Containing changes in Attributes and adding Slot Rules
  Tormenta20 - Jogo do Ano/sheet.json
  Tormenta20 - Jogo do Ano/tormenta20.css
  Tormenta20 - Jogo do Ano/tormenta20.html
  Tormenta20 - Jogo do Ano/tormenta20.png
  Tormenta20 - Jogo do Ano/translation.json
  Tormenta20 - Jogo do Ano/translations/af.json
  Tormenta20 - Jogo do Ano/translations/ca.json
  Tormenta20 - Jogo do Ano/translations/cs.json
  Tormenta20 - Jogo do Ano/translations/da.json
  Tormenta20 - Jogo do Ano/translations/de.json
  Tormenta20 - Jogo do Ano/translations/el.json
  Tormenta20 - Jogo do Ano/translations/en.json
  Tormenta20 - Jogo do Ano/translations/es.json
  Tormenta20 - Jogo do Ano/translations/fi.json
  Tormenta20 - Jogo do Ano/translations/fr.json
  Tormenta20 - Jogo do Ano/translations/he.json
  Tormenta20 - Jogo do Ano/translations/hu.json
  Tormenta20 - Jogo do Ano/translations/it.json
  Tormenta20 - Jogo do Ano/translations/ja.json
  Tormenta20 - Jogo do Ano/translations/ko.json
  Tormenta20 - Jogo do Ano/translations/nl.json
  Tormenta20 - Jogo do Ano/translations/pb.json
  Tormenta20 - Jogo do Ano/translations/pl.json
  Tormenta20 - Jogo do Ano/translations/pt.json
  Tormenta20 - Jogo do Ano/translations/ru.json
  Tormenta20 - Jogo do Ano/translations/sl.json
  Tormenta20 - Jogo do Ano/translations/sv.json
  Tormenta20 - Jogo do Ano/translations/tr.json
  Tormenta20 - Jogo do Ano/translations/uk.json
  Tormenta20 - Jogo do Ano/translations/zh.json
Labels: new sheet

#11125 Court Of Blades: Add sheet
  Court Of Blades/CourtOfBlades.css
  Court Of Blades/CourtOfBlades.html
  Court Of Blades/preview.png
  Court Of Blades/sheet.json
  Court Of Blades/translation.json
Labels: passed

#11128 [Tormenta20 - Jogo do Ano] Updated Logo, view changes and added diferent roll types
  Tormenta20 - Jogo do Ano/Tormenta20Logo.png
  Tormenta20 - Jogo do Ano/tormenta20.css
  Tormenta20 - Jogo do Ano/tormenta20.html
  Tormenta20 - Jogo do Ano/tormenta20.png
  Tormenta20 - Jogo do Ano/translation.json
Labels: new sheet

#11152 [Grimoire of the Heart] Added new sheet
  Grimoire of the Heart/README.md
  Grimoire of the Heart/assets/credits.txt
  Grimoire of the Heart/assets/dark.PNG
  Grimoire of the Heart/assets/fire.PNG
  Grimoire of the Heart/assets/grimoire-logo.png
  Grimoire of the Heart/assets/ice.PNG
  Grimoire of the Heart/assets/intel.PNG
  Grimoire of the Heart/assets/light.PNG
  Grimoire of the Heart/assets/nuclear.PNG
  Grimoire of the Heart/assets/physical.PNG
  Grimoire of the Heart/assets/psychokinetic.PNG
  Grimoire of the Heart/assets/skull.svg
  Grimoire of the Heart/assets/status.PNG
  Grimoire of the Heart/assets/thunder.PNG
  Grimoire of the Heart/assets/wind.PNG
  Grimoire of the Heart/preview.png
  Grimoire of the Heart/sheet.css
  Grimoire of the Heart/sheet.html
  Grimoire of the Heart/sheet.json
  Grimoire of the Heart/translation.json
Labels: new sheet
