Repository Roll20/roll20-character-sheets, pull requests merged in 2023-12, with the labels that each got.

#12358 Maleghast New Sheet
  Maleghast/Maleghast.css
  Maleghast/Maleghast.html
  Maleghast/Maleghast.jpg
  Maleghast/sheet.json
Labels: approved yaml change

#12338 New sheet for Onyx Path's The World Below
  The World Below/TWB.jpg
  The World Below/TWB_CSS.css
  The World Below/TWB_HTML.html
  The World Below/TWB_Translation.json
  The World Below/sheet.json
Labels: approved yaml change

#12369 Talus - New Sheet
  Talus/images/talus-border_dark-mode.png
  Talus/images/talus-border_light-mode.png
  Talus/images/talus-dagger_dark-mode.png
  Talus/images/talus-dagger_light-mode.png
  Talus/images/talus-footer_dark-mode.png
  Talus/images/talus-footer_light-mode.png
  Talus/images/talus-header_dark-mode.png
  Talus/images/talus-header_light-mode.png
  Talus/images/talus-ornament_dark-mode.png
  Talus/images/talus-ornament_light-mode.png
  Talus/images/talus-pnp-logo.png
  Talus/images/talus-pnp-ornament-01.png
  Talus/images/talus-trenner_dark-mode.png
  Talus/images/talus-trenner_light-mode.png
  Talus/images/talus_wuerfel-icon.png
  Talus/sheet-preview-darkmode.png
  Talus/sheet-preview.png
  Talus/sheet.json
  Talus/talus-pnp-logo.png
  Talus/talus.css
  Talus/talus.html
Labels: approved yaml change

#12360 Star Wars Saga Edition (New Features/Bug Fixes)
  Star Wars Saga Edition/StarWarsSagaEdition.css
  Star Wars Saga Edition/StarWarsSagaEdition.html
  Star Wars Saga Edition/sheet.json
  Star Wars Saga Edition/translation.json
Labels: blocked

#12384 [Dragon Riders] New Sheet
  Dragon_Riders/Fonts/IMFE.ttf
  Dragon_Riders/Fonts/im-fell-english-roman.ttf
  Dragon_Riders/Images/logo.png
  Dragon_Riders/Images/sygnet-red.png
  Dragon_Riders/dragonriders.css
  Dragon_Riders/dragonriders.html
  Dragon_Riders/preview.jpg
  Dragon_Riders/sheet.json
  Dragon_Riders/translation.json
Labels: new sheet

#12403 [New Sheet] Blue Archive Game
  Blue Archive/BlueArchive.css
  Blue Archive/BlueArchive.html
  Blue Archive/BlueArchive.png
  Blue Archive/sheet.json
Labels: approved yaml change
