Repository Roll20/roll20-character-sheets, pull requests merged in 2023-11, with the labels that each got.

#12275 [Ironsworn: Starforged] [Fix] Oracles missed due to data restructure
  Ironsworn-Starforged/Ironsworn-starforged.html
  Ironsworn-Starforged/src/app/components/oracles/mixins/oracle-roll-btn.pug
  Ironsworn-Starforged/src/app/components/oracles/oracle-preview.pug
  Ironsworn-Starforged/src/app/pages/character/oracles.pug
  Ironsworn-Starforged/src/app/roll-templates/oracles/builder.pug
  Ironsworn-Starforged/src/app/translations/translation-oracles.json
  Ironsworn-Starforged/src/buildTranslations.js
  Ironsworn-Starforged/translation.json
Labels: being reviewed

#12285 Paranoia (Perfect Edition) character sheet - v1.00.01 and character sheet required images - New Sheet
  Paranoia Perfect Edition Official/LICENSE
  Paranoia Perfect Edition Official/Official Mongoose Publishing Paranoia Character Sheet Naughty Side.jpg
  Paranoia Perfect Edition Official/Official Mongoose Publishing Paranoia Character Sheet.css
  Paranoia Perfect Edition Official/Official Mongoose Publishing Paranoia Character Sheet.html
  Paranoia Perfect Edition Official/Official Mongoose Publishing Paranoia Character Sheet.jpg
  Paranoia Perfect Edition Official/README.md
  Paranoia Perfect Edition Official/character-sheet-eye.jpg
  Paranoia Perfect Edition Official/character-sheet-header.jpg
  Paranoia Perfect Edition Official/character-sheet-naughty-header.jpg
  Paranoia Perfect Edition Official/friend-computer-eye.png
  Paranoia Perfect Edition Official/sheet.json
  Paranoia Perfect Edition Official/translation.json
Labels: approved yaml change

#12282 Update en.json
  Warlock Polish Edition/translation.json
Labels: blocked

#12312 (New Character Sheet) The Fade Tabletop 3rd Edition
  The Fade 3e/TheFade3e.css
  The Fade 3e/TheFade3e.html
  The Fade 3e/TheFade3e.png
  The Fade 3e/sheet.json
Labels: approved yaml change

#12321 Adding Table Top Defined Sheet
  Table Top Defined/Example_Image.png
  Table Top Defined/Table_Top_Defined.css
  Table Top Defined/Table_Top_Defined.html
  Table Top Defined/sheet.json
Labels: approved yaml change
