Repository Roll20/roll20-character-sheets, pull requests merged in 2024-10, with the labels that each got.

#13344 Update Arc Doom translation.json
  ARC/translation.json
Labels: blocked

#13357 New Sheet for "Rivers Of London"
  Rivers_Of_London/rol-preview.png
  Rivers_Of_London/rol.css
  Rivers_Of_London/rol.html
  Rivers_Of_London/sheet.json
Labels: new sheet

#13365 [Project Moon TRPG] Re-release v0.7
  ProjectMoonTRPG/ProjectMoonTRPG.html
  ProjectMoonTRPG/ProjectMoonTRPGStyle.css
  ProjectMoonTRPG/images/ailments/limbus/DamageDown.png
  ProjectMoonTRPG/images/ailments/limbus/DamageUp.png
  ProjectMoonTRPG/images/community/Frenzy.png
  ProjectMoonTRPG/images/community/Shock.png
  ProjectMoonTRPG/images/community/StaggerDamageDown.png
  ProjectMoonTRPG/images/community/StaggerDamageUp.png
  ProjectMoonTRPG/images/community/Terror.png
  ProjectMoonTRPG/imagesResized/ailments/limbus/DamageDown.png
  ProjectMoonTRPG/imagesResized/ailments/limbus/DamageUp.png
  ProjectMoonTRPG/imagesResized/community/Frenzy.png
  ProjectMoonTRPG/imagesResized/community/Shock.png
  ProjectMoonTRPG/imagesResized/community/StaggerDamageDown.png
  ProjectMoonTRPG/imagesResized/community/StaggerDamageUp.png
  ProjectMoonTRPG/imagesResized/community/Terror.png
  ProjectMoonTRPG/sheet.json
  ProjectMoonTRPG/translation.json
Labels: blocked

#13384 Mongoose Traveller 2e Official - Update and Bug Fixes
  Mongoose Traveller 2e Official/Official Mongoose Publishing Traveller 2nd Edition.css
  Mongoose Traveller 2e Official/Official Mongoose Publishing Traveller 2nd Edition.html
  Mongoose Traveller 2e Official/Official Mongoose Publishing Traveller 2nd Edition.png
  Mongoose Traveller 2e Official/README.md
  Mongoose Traveller 2e Official/translation.json
Labels: new sheet

#13380 [Lames du Cardinal v2] New sheet
  Lames du Cardinal v2/.gitignore
  Lames du Cardinal v2/assets/dragonnoir.jpg
  Lames du Cardinal v2/assets/dragonrouge.jpg
  Lames du Cardinal v2/assets/ecaille.png
  Lames du Cardinal v2/assets/epee.png
  Lames du Cardinal v2/assets/griffe.png
  Lames du Cardinal v2/assets/sang.png
  Lames du Cardinal v2/assets/souffle.png
  Lames du Cardinal v2/lames_cardinal.css
  Lames du Cardinal v2/lames_cardinal.html
  Lames du Cardinal v2/package-lock.json
  Lames du Cardinal v2/package.json
  Lames du Cardinal v2/preview.png
  Lames du Cardinal v2/sheet.json
  Lames du Cardinal v2/src/abstracts/_layout.sass
  Lames du Cardinal v2/src/abstracts/_mixins.sass
  Lames du Cardinal v2/src/abstracts/_typography.sass
  Lames du Cardinal v2/src/abstracts/variables.sass
  Lames du Cardinal v2/src/components/blessedarcana/blessedarcana.js
  Lames du Cardinal v2/src/components/blessedarcana/blessedarcana.pug
  Lames du Cardinal v2/src/components/blessedarcana/blessedarcana.sass
  Lames du Cardinal v2/src/components/carac/carac.js
  Lames du Cardinal v2/src/components/carac/carac.pug
  Lames du Cardinal v2/src/components/carac/carac.sass
  Lames du Cardinal v2/src/components/components.pug
  Lames du Cardinal v2/src/components/components.sass
  Lames du Cardinal v2/src/components/fillleft/fillleft.pug
  Lames du Cardinal v2/src/components/fillleft/fillleft.sass
  Lames du Cardinal v2/src/components/nstatebox/nstatebox.js
  Lames du Cardinal v2/src/components/nstatebox/nstatebox.pug
  Lames du Cardinal v2/src/components/nstatebox/nstatebox.sass
  Lames du Cardinal v2/src/components/profile/profile.pug
  Lames du Cardinal v2/src/components/profile/profile.sass
  Lames du Cardinal v2/src/components/skill/skill.js
  Lames du Cardinal v2/src/components/skill/skill.pug
  Lames du Cardinal v2/src/components/skill/skill.sass
  Lames du Cardinal v2/src/components/swordbar/swordbar.js
  Lames du Cardinal v2/src/components/swordbar/swordbar.pug
  Lames du Cardinal v2/src/components/swordbar/swordbar.sass
  Lames du Cardinal v2/src/components/widgets/widgets.pug
  Lames du Cardinal v2/src/components/widgets/widgets.sass
  Lames du Cardinal v2/src/init.js
  Lames du Cardinal v2/src/lames_cardinal.pug
  Lames du Cardinal v2/src/lames_cardinal.sass
  Lames du Cardinal v2/src/modules/1-personnage/personnage.js
  Lames du Cardinal v2/src/modules/1-personnage/personnage.pug
  Lames du Cardinal v2/src/modules/1-personnage/personnage.sass
  Lames du Cardinal v2/src/modules/2-competences/competences.js
  Lames du Cardinal v2/src/modules/2-competences/competences.pug
  Lames du Cardinal v2/src/modules/2-competences/competences.sass
  Lames du Cardinal v2/src/modules/3-escrime/escrime.pug
  Lames du Cardinal v2/src/modules/3-escrime/escrime.sass
  Lames du Cardinal v2/src/modules/4-ressources/ressources.pug
  Lames du Cardinal v2/src/modules/4-ressources/ressources.sass
Labels: new sheet

#13367 Add Sphere Child 3rd Edition character sheet (German)
  Sphere Child/sheet.json
  Sphere Child/spherechild.css
  Sphere Child/spherechild.html
  Sphere Child/spherechild_preview.png
Labels: new sheet

#13385 New Crowdin updates
  ARC/translations/fr.json
  Coriolis/translations/pl.json
  Cthulhu Eternal/translations/fr.json
  Fallout 2d20/translations/es.json
  Mongoose Traveller 2e Official/translations/af.json
  Mongoose Traveller 2e Official/translations/ca.json
  Mongoose Traveller 2e Official/translations/cs.json
  Mongoose Traveller 2e Official/translations/da.json
  Mongoose Traveller 2e Official/translations/de.json
  Mongoose Traveller 2e Official/translations/el.json
  Mongoose Traveller 2e Official/translations/en.json
  Mongoose Traveller 2e Official/translations/es.json
  Mongoose Traveller 2e Official/translations/fi.json
  Mongoose Traveller 2e Official/translations/fr.json
  Mongoose Traveller 2e Official/translations/he.json
  Mongoose Traveller 2e Official/translations/hu.json
  Mongoose Traveller 2e Official/translations/it.json
  Mongoose Traveller 2e Official/translations/ja.json
  Mongoose Traveller 2e Official/translations/ko.json
  Mongoose Traveller 2e Official/translations/nl.json
  Mongoose Traveller 2e Official/translations/pb.json
  Mongoose Traveller 2e Official/translations/pl.json
  Mongoose Traveller 2e Official/translations/pt.json
  Mongoose Traveller 2e Official/translations/ru.json
  Mongoose Traveller 2e Official/translations/sl.json
  Mongoose Traveller 2e Official/translations/sv.json
  Mongoose Traveller 2e Official/translations/tr.json
  Mongoose Traveller 2e Official/translations/uk.json
  Mongoose Traveller 2e Official/translations/zh.json
  Pathfinder 2 Playtest by Roll20/translations/da.json
Labels: new sheet

#13358 Update sheet.html with Battle Dancer Class
  Sword World/sheet.html
Labels: being reviewed

#13359 Update sheet.json
  Sword World/sheet.json
Labels: being reviewed

#13420 [MEDIEVO OSCURO] Weapon damage changed to a text field instead select class:"dtype"
  Medievo Oscuro/medievooscuro.html
Labels: blocked

#13416 New Sheet - Fragged Empire 2E
  Fragged-Empire 2E/Character.png
  Fragged-Empire 2E/FraggedEmpire2E.css
  Fragged-Empire 2E/FraggedEmpire2E.html
  Fragged-Empire 2E/sheet.json
Labels: blocked

#13434 Rivers of London - bug fixes and new features
  Rivers_Of_London/rol-preview.png
  Rivers_Of_London/rol.css
  Rivers_Of_London/rol.html
  Rivers_Of_London/sheet.json
Labels: new sheet

#13432 Aetherial Expanse: Release
  aetherial_expanse/Aetherial Expanse Preview.jpg
  aetherial_expanse/aetherial_expanse.css
  aetherial_expanse/aetherial_expanse.html
  aetherial_expanse/sheet.json
  aetherial_expanse/translation.json
Labels: new sheet
