Repository Roll20/roll20-character-sheets, pull requests merged in 2024-12, with the labels that each got.

#13512 Draci doupe II – token markers for "load" attribute
  Draci doupe II/assets/DrD2-token_markers/loadL.png
  Draci doupe II/assets/DrD2-token_markers/loadS.png
  Draci doupe II/assets/DrD2-token_markers/loadT.png
Labels: being resolved

#13588 StargateSG-1 - Bugfix
  StargateSG-1/Readme.down
  StargateSG-1/StargateSG-1.html
Labels: blocked

#13595 New Sheet d20age RPG
  d20age/d20age.css
  d20age/d20age.html
  d20age/d20age.png
  d20age/images/d20agelogo.png
  d20age/images/pencil-scribble-banner-3.png
  d20age/sheet.json
Labels: approved yaml change

#13610 Bugfixes [Scion 1e]
  Scion/Scion.html
Labels: blocked
