Repository Roll20/roll20-character-sheets, pull requests merged in 2024-02, with the labels that each got.

#12580 [NEW SHEET] Le Cabinet des Murmures
  Cabinet des Murmures/Readme.md
  Cabinet des Murmures/cabinet_des_murmures.css
  Cabinet des Murmures/cabinet_des_murmures.html
  Cabinet des Murmures/cabinet_des_murmures.png
  Cabinet des Murmures/img/2D6_checked.png
  Cabinet des Murmures/img/2D6_unchecked.png
  Cabinet des Murmures/img/cdm_bleu.png
  Cabinet des Murmures/img/cdm_jaune.png
  Cabinet des Murmures/img/cdm_rouge.png
  Cabinet des Murmures/img/cdm_vert.png
  Cabinet des Murmures/img/cdm_violet.png
  Cabinet des Murmures/img/deco_bottom.PNG
  Cabinet des Murmures/img/deco_right.PNG
  Cabinet des Murmures/img/intro_esprit.jpg
  Cabinet des Murmures/img/intro_medium.jpg
  Cabinet des Murmures/img/intro_pnj.jpg
  Cabinet des Murmures/img/offi_arbre_de_vie_ouija.jpg
  Cabinet des Murmures/img/offi_arbre_qualite.png
  Cabinet des Murmures/img/offi_background.png
  Cabinet des Murmures/img/offi_background_name.png
  Cabinet des Murmures/img/offi_button_background.png
  Cabinet des Murmures/img/offi_button_background_result.png
  Cabinet des Murmures/img/offi_button_dice_tab_checked.png
  Cabinet des Murmures/img/offi_button_dice_tab_unchecked.png
  Cabinet des Murmures/img/offi_button_loupe_tab_checked.png
  Cabinet des Murmures/img/offi_button_loupe_tab_unchecked.png
  Cabinet des Murmures/img/offi_malus_cadre.png
  Cabinet des Murmures/img/offi_malus_cadre_pnj1.png
  Cabinet des Murmures/img/offi_man.png
  Cabinet des Murmures/img/offi_qualite_esprit.png
  Cabinet des Murmures/img/offi_result_deco.png
  Cabinet des Murmures/img/offi_separateur_petit.png
  Cabinet des Murmures/img/offi_separateur_vertical.png
  Cabinet des Murmures/img/offi_title-border-long-red.png
  Cabinet des Murmures/img/offi_title-border-long.png
  Cabinet des Murmures/img/offi_title-border.png
  Cabinet des Murmures/img/offi_woman.png
  Cabinet des Murmures/img/offi_xp_esprit.png
  Cabinet des Murmures/img/reset_perisprit.png
  Cabinet des Murmures/img/xp_border.png
  Cabinet des Murmures/sheet.json
  Cabinet des Murmures/translation.json
Labels: approved yaml change, blocked

#12578 [Cthulhu No Kami] New Sheet
  Cthulhu No Kami/cnkPreview.png
  Cthulhu No Kami/cthulhunokami.css
  Cthulhu No Kami/cthulhunokami.html
  Cthulhu No Kami/img/arrow.png
  Cthulhu No Kami/img/contact.png
  Cthulhu No Kami/img/defense.png
  Cthulhu No Kami/img/distance.png
  Cthulhu No Kami/img/initiative.png
  Cthulhu No Kami/img/magique.png
  Cthulhu No Kami/img/resistance.png
  Cthulhu No Kami/pug/cthulhunokami.pug
  Cthulhu No Kami/pug/js/_library.js
  Cthulhu No Kami/pug/js/combat.js
  Cthulhu No Kami/pug/js/fixe.js
  Cthulhu No Kami/pug/js/inventaire.js
  Cthulhu No Kami/pug/js/popup.js
  Cthulhu No Kami/pug/js/profil.js
  Cthulhu No Kami/pug/js/vehicules.js
  Cthulhu No Kami/pug/js/voies.js
  Cthulhu No Kami/pug/parts/combat.pug
  Cthulhu No Kami/pug/parts/etats.pug
  Cthulhu No Kami/pug/parts/inventaire.pug
  Cthulhu No Kami/pug/parts/popup.pug
  Cthulhu No Kami/pug/parts/profil.pug
  Cthulhu No Kami/pug/parts/traits.pug
  Cthulhu No Kami/pug/parts/vehicules.pug
  Cthulhu No Kami/pug/parts/voies.pug
  Cthulhu No Kami/pug/templates/combat.html
  Cthulhu No Kami/pug/templates/niveau.html
  Cthulhu No Kami/pug/templates/std.html
  Cthulhu No Kami/scss/cthulhunokami.scss
  Cthulhu No Kami/scss/files/_library.scss
  Cthulhu No Kami/scss/files/base.scss
  Cthulhu No Kami/scss/files/combat.scss
  Cthulhu No Kami/scss/files/etats.scss
  Cthulhu No Kami/scss/files/inventaire.scss
  Cthulhu No Kami/scss/files/popup.scss
  Cthulhu No Kami/scss/files/profil.scss
  Cthulhu No Kami/scss/files/sheet.scss
  Cthulhu No Kami/scss/files/templates.scss
  Cthulhu No Kami/scss/files/traits.scss
  Cthulhu No Kami/scss/files/vehicules.scss
  Cthulhu No Kami/scss/files/voies.scss
  Cthulhu No Kami/sheet.json
  Cthulhu No Kami/translation.json
Labels: new sheet

#12595 [Stewpot] New Sheet
  Stewpot/Stewpot.css
  Stewpot/Stewpot.html
  Stewpot/Stewpot.png
  Stewpot/sheet.json
  Stewpot/translation.json
Labels: approved yaml change
