Repository Roll20/roll20-character-sheets, pull requests merged in 2024-01, with the labels that each got.

#12400 Fabula Ultima: sheet update and improvement
  Fabula Ultima/FabulaUltima.css
  Fabula Ultima/FabulaUltima.html
  Fabula Ultima/FabulaUltima.png
  Fabula Ultima/sheet.json
Labels: being reviewed

#12432 [CoureursD’Orages] Creation of the new sheet
  Coureurs-d-Orages/Coureurs-d-Orages.css
  Coureurs-d-Orages/Coureurs-d-Orages.html
  Coureurs-d-Orages/Coureurs-d-Orages.png
  Coureurs-d-Orages/sheet.json
Labels: approved yaml change

#12449 Update ko.json, ShinobiGami.html, ShinobiGami.css
  Shinobi_Gami_Chinese_Traditional/ShinobiGami.css
  Shinobi_Gami_Chinese_Traditional/ShinobiGami.html
  Shinobi_Gami_Chinese_Traditional/translations/ko.json
Labels: blocked

#12471 Gaia - Create
  Gaia/assets/gaia-logo.png
  Gaia/assets/recurso-max.png
  Gaia/gaia.css
  Gaia/gaia.html
  Gaia/gaia.png
  Gaia/sheet.json
Labels: approved yaml change
