Repository Roll20/roll20-character-sheets, pull requests merged in 2024-04, with the labels that each got.

#12757 [NEW SHEET] Notre Tombeau
  Notre tombeau/images/back1.png
  Notre tombeau/images/background_roll.jpg
  Notre tombeau/images/background_rolltemplate.jpg
  Notre tombeau/images/dice_arme.png
  Notre tombeau/notre_tombeau.css
  Notre tombeau/notre_tombeau.html
  Notre tombeau/notre_tombeau.png
  Notre tombeau/readme.md
  Notre tombeau/sheet.json
Labels: approved yaml change

#12777 [New Sheet] Fur & Forge
  Fur & Forge/Fur&Forge.css
  Fur & Forge/Fur&Forge.html
  Fur & Forge/Fur&Forge.png
  Fur & Forge/sheet.json
Labels: approved yaml change

#12779 [New Sheet] Roll for Shoes
  Roll for Shoes/preview.png
  Roll for Shoes/sheet.html
  Roll for Shoes/sheet.json
  Roll for Shoes/styles.css
Labels: blocked

#12831 [Layout Changes][Bug Fix][Skyfall] Updating in all Character Sheet Style
  Skyfall/ficha.html
  Skyfall/imgs/acao.svg
  Skyfall/imgs/bonus.svg
  Skyfall/imgs/reacao.svg
  Skyfall/skyfall.css
Labels: blocked

#12819 AD&D 1e Revised Sheet
  ADnD_1E_Revised/1ESheet.css
  ADnD_1E_Revised/1ESheet.html
  ADnD_1E_Revised/1ESheet.jpg
  ADnD_1E_Revised/images/back2.jpg
  ADnD_1E_Revised/images/logo.png
  ADnD_1E_Revised/images/logo_inverted.png
  ADnD_1E_Revised/sheet.json
Labels: new sheet
