Repository Roll20/roll20-character-sheets, pull requests merged in 2025-08, with the labels that each got.

#14237 [Streets of Jade (Playtest)] New Sheet: Initial Upload
  Streets of Jade (Playtest)/jade.css
  Streets of Jade (Playtest)/jade.html
  Streets of Jade (Playtest)/jade.png
  Streets of Jade (Playtest)/sheet.json
  Streets of Jade (Playtest)/translation.json
Labels: approved yaml change

#14250 Neuroshima Rok Malacha | Updating sheet.json to force re-run
  Neuroshima Rok Molocha/sheet.json
Labels: R20 maintenance

#14282 Updating Blood and Doom official sheet
  Blood_and_Doom_by_Dicetale_Games/.gitignore
  Blood_and_Doom_by_Dicetale_Games/.prettierignore
  Blood_and_Doom_by_Dicetale_Games/.prettierrc
  Blood_and_Doom_by_Dicetale_Games/README.md
  Blood_and_Doom_by_Dicetale_Games/package-lock.json
  Blood_and_Doom_by_Dicetale_Games/package.json
  Blood_and_Doom_by_Dicetale_Games/src/Roll20.d.ts
  Blood_and_Doom_by_Dicetale_Games/src/bloodanddoom.pug
  Blood_and_Doom_by_Dicetale_Games/src/pug/character.pug
  Blood_and_Doom_by_Dicetale_Games/src/pug/header.pug
  Blood_and_Doom_by_Dicetale_Games/src/pug/mixins.pug
  Blood_and_Doom_by_Dicetale_Games/src/pug/options.pug
  Blood_and_Doom_by_Dicetale_Games/src/pug/path.pug
  Blood_and_Doom_by_Dicetale_Games/src/pug/rolltemplates.pug
  Blood_and_Doom_by_Dicetale_Games/src/styles.scss
  Blood_and_Doom_by_Dicetale_Games/src/ts/actions.ts
  Blood_and_Doom_by_Dicetale_Games/src/ts/calculations.ts
  Blood_and_Doom_by_Dicetale_Games/src/ts/events.ts
  Blood_and_Doom_by_Dicetale_Games/src/ts/rolls.ts
  Blood_and_Doom_by_Dicetale_Games/src/ts/utils.ts
  Blood_and_Doom_by_Dicetale_Games/src/ts/visibility-toggles.ts
  Blood_and_Doom_by_Dicetale_Games/static/add.svg
  Blood_and_Doom_by_Dicetale_Games/static/avatar.png
  Blood_and_Doom_by_Dicetale_Games/static/check.svg
  Blood_and_Doom_by_Dicetale_Games/static/cog.svg
  Blood_and_Doom_by_Dicetale_Games/static/d10.svg
  Blood_and_Doom_by_Dicetale_Games/static/d10die.svg
  Blood_and_Doom_by_Dicetale_Games/static/dented.svg
  Blood_and_Doom_by_Dicetale_Games/static/hash.svg
  Blood_and_Doom_by_Dicetale_Games/static/heart-crack.svg
  Blood_and_Doom_by_Dicetale_Games/static/lock-open.svg
  Blood_and_Doom_by_Dicetale_Games/static/lock.svg
  Blood_and_Doom_by_Dicetale_Games/static/logo.svg
  Blood_and_Doom_by_Dicetale_Games/static/logo_1300_inline_bw.png
  Blood_and_Doom_by_Dicetale_Games/static/shield--empty.png
  Blood_and_Doom_by_Dicetale_Games/static/shield-slash.svg
  Blood_and_Doom_by_Dicetale_Games/static/shield.png
  Blood_and_Doom_by_Dicetale_Games/static/shield.svg
  Blood_and_Doom_by_Dicetale_Games/static/xmark--red.svg
  Blood_and_Doom_by_Dicetale_Games/static/xmark.svg
  Blood_and_Doom_by_Dicetale_Games/tsconfig.json
Labels: blocked
