Repository Roll20/roll20-character-sheets, pull requests merged in 2025-04, with the labels that each got.

#13900 Mongoose Publishing Traveller 2e Official - Updated Character Sheet v1.1.01
  Mongoose Traveller 2e Official/Official Mongoose Publishing Traveller 2nd Edition.css
  Mongoose Traveller 2e Official/Official Mongoose Publishing Traveller 2nd Edition.html
  Mongoose Traveller 2e Official/Official Mongoose Publishing Traveller 2nd Edition.png
  Mongoose Traveller 2e Official/README.md
  Mongoose Traveller 2e Official/sheet.json
  Mongoose Traveller 2e Official/translation.json
Labels: new sheet

#13916 New Crowdin updates
  Mongoose Traveller 2e Official/translations/af.json
  Mongoose Traveller 2e Official/translations/ca.json
  Mongoose Traveller 2e Official/translations/cs.json
  Mongoose Traveller 2e Official/translations/da.json
  Mongoose Traveller 2e Official/translations/de.json
  Mongoose Traveller 2e Official/translations/el.json
  Mongoose Traveller 2e Official/translations/en.json
  Mongoose Traveller 2e Official/translations/es.json
  Mongoose Traveller 2e Official/translations/fi.json
  Mongoose Traveller 2e Official/translations/fr.json
  Mongoose Traveller 2e Official/translations/he.json
  Mongoose Traveller 2e Official/translations/hu.json
  Mongoose Traveller 2e Official/translations/it.json
  Mongoose Traveller 2e Official/translations/ja.json
  Mongoose Traveller 2e Official/translations/ko.json
  Mongoose Traveller 2e Official/translations/nl.json
  Mongoose Traveller 2e Official/translations/pb.json
  Mongoose Traveller 2e Official/translations/pl.json
  Mongoose Traveller 2e Official/translations/pt.json
  Mongoose Traveller 2e Official/translations/ru.json
  Mongoose Traveller 2e Official/translations/sl.json
  Mongoose Traveller 2e Official/translations/sv.json
  Mongoose Traveller 2e Official/translations/tr.json
  Mongoose Traveller 2e Official/translations/uk.json
  Mongoose Traveller 2e Official/translations/zh.json
Labels: new sheet

#13861 New Sheet: Dragonslayer_Unofficial
  Dragonslayer_Unofficial/DragonslayerSheet.css
  Dragonslayer_Unofficial/DragonslayerSheet.html
  Dragonslayer_Unofficial/DragonslayerSheetPreview.png
  Dragonslayer_Unofficial/dragonslayer_spells.json
  Dragonslayer_Unofficial/sheet.json
Labels: new sheet

#13938 Mongoose Publishing Traveller 2e Official - Updated Character Sheet v1.1.02
  Mongoose Traveller 2e Official/Official Mongoose Publishing Traveller 2nd Edition.css
  Mongoose Traveller 2e Official/Official Mongoose Publishing Traveller 2nd Edition.html
  Mongoose Traveller 2e Official/README.md
  Mongoose Traveller 2e Official/translation.json
Labels: Awaiting Verification

#13960 [Vaesen Official] sheet launch
  vaesen_official/sheet.json
  vaesen_official/translation.json
  vaesen_official/vaesen.css
  vaesen_official/vaesen.html
  vaesen_official/vaesen.jpg
Labels: approved yaml change

#13954 Atualização ficha Daemon Exilia
  Daemon Exilia/Exilia.css
  Daemon Exilia/Exilia.html
  Daemon Exilia/sheet.js
  Daemon Exilia/sheet.json
Labels: blocked

#13955 [NetBattlers] New Sheet: Add sheet for NetBattlers
  NetBattlers/NetBattlersSheet.css
  NetBattlers/NetBattlersSheet.html
  NetBattlers/NetBattlersSheet_Preview.png
  NetBattlers/sheet.json
Labels: blocked, Awaiting Verification

#13933 [Dicey Tales] New sheet
  Dicey Tales/dicey_tales.css
  Dicey Tales/dicey_tales.html
  Dicey Tales/preview.png
  Dicey Tales/sheet.json
Labels: approved yaml change, blocked

#13964 Naruto JDR (fanmade)
  Naruto JDR/README.md
  Naruto JDR/preview.png
  Naruto JDR/sheet.css
  Naruto JDR/sheet.html
  Naruto JDR/sheet.js
  Naruto JDR/sheet.json
Labels: approved yaml change
