Repository Roll20/roll20-character-sheets, pull requests merged in 2025-07, with the labels that each got.

#14191 D6++ Wild West - fixed spelling mistake
  D6pp_Wild_West/d6ppww.html
Labels: being reviewed

#14197 [Mythic Bastionland] Bugfix: Various fixes and improvements
  Mythic-Bastionland/images/page bg.jpg
  Mythic-Bastionland/mythic-bastionland.css
  Mythic-Bastionland/mythic-bastionland.html
  Mythic-Bastionland/mythic-bastionland.png
  Mythic-Bastionland/sheet.json
Labels: being reviewed

#14128 Roll20 PR | Fix Adventures on a Dime
  Adventures on a Dime/adventures-on-a-dime.css
  Adventures on a Dime/adventures-on-a-dime.html
  Adventures on a Dime/sheet.json
  Adventures on a Dime/translation.json
Labels: R20 maintenance

#14199 [Space Horror Stories] New character sheet
  Space Horror Stories/.gitignore
  Space Horror Stories/README.md
  Space Horror Stories/img/astronaut-helmet.png
  Space Horror Stories/img/carrure.png
  Space Horror Stories/img/heart-beats.png
  Space Horror Stories/img/kevlar-vest.png
  Space Horror Stories/img/motricite.png
  Space Horror Stories/img/relationel.png
  Space Horror Stories/img/sangfroid.png
  Space Horror Stories/img/science.png
  Space Horror Stories/package-lock.json
  Space Horror Stories/package.json
  Space Horror Stories/preview.png
  Space Horror Stories/sheet.json
  Space Horror Stories/shs.css
  Space Horror Stories/shs.css.map
  Space Horror Stories/shs.html
  Space Horror Stories/src/components/ability.pug
  Space Horror Stories/src/components/ability.sass
  Space Horror Stories/src/components/numovermax.pug
  Space Horror Stories/src/components/numovermax.sass
  Space Horror Stories/src/components/panel.pug
  Space Horror Stories/src/components/panel.sass
  Space Horror Stories/src/components/relation.pug
  Space Horror Stories/src/components/relation.sass
  Space Horror Stories/src/components/vars.sass
  Space Horror Stories/src/components/weapons.pug
  Space Horror Stories/src/components/weapons.sass
  Space Horror Stories/src/components/widgets.pug
  Space Horror Stories/src/components/widgets.sass
  Space Horror Stories/src/components/wounds.pug
  Space Horror Stories/src/components/wounds.sass
  Space Horror Stories/src/init.js
  Space Horror Stories/src/js/ability.js
  Space Horror Stories/src/js/combat.js
  Space Horror Stories/src/js/dice.js
  Space Horror Stories/src/js/namechange.js
  Space Horror Stories/src/js/sections.js
  Space Horror Stories/src/js/wounds.js
  Space Horror Stories/src/rolltemplates/attack.html
  Space Horror Stories/src/rolltemplates/burndamage.html
  Space Horror Stories/src/rolltemplates/damage.html
  Space Horror Stories/src/rolltemplates/goldorak.html
  Space Horror Stories/src/rolltemplates/rolltemplates.sass
  Space Horror Stories/src/rolltemplates/simple.html
  Space Horror Stories/src/shs.pug
  Space Horror Stories/src/shs.sass
Labels: approved yaml change
