Repository Roll20/roll20-character-sheets, pull requests merged in 2025-09, with the labels that each got.

#14325 Mongoose Traveller 2e Official - Version 1.1.08
  Mongoose Traveller 2e Official/Official Mongoose Publishing Traveller 2nd Edition.html
  Mongoose Traveller 2e Official/README.md
Labels: blocked

#14352 D6++ Modern d6pp_Modern New Sheet
  D6pp_Modern/d6ppmodern.css
  D6pp_Modern/d6ppmodern.html
  D6pp_Modern/d6ppmodern.png
  D6pp_Modern/sheet.json
Labels: approved yaml change

#14358 [Perils and Princesses] Semi-New Sheet
  Perils and Princesses/Graphics/perilArmor.png
  Perils and Princesses/Graphics/perilBanner.png
  Perils and Princesses/Graphics/perilFlowerBorder.jpg
  Perils and Princesses/Graphics/perilFrame.png
  Perils and Princesses/Graphics/perilHeart.png
  Perils and Princesses/Graphics/perilLace1.png
  Perils and Princesses/Graphics/perilLace2.png
  Perils and Princesses/Graphics/perilLace3.png
  Perils and Princesses/Graphics/perilSword.png
  Perils and Princesses/Graphics/perilTrauma.png
  Perils and Princesses/Graphics/perilTriangles.png
  Perils and Princesses/Perils.css
  Perils and Princesses/Perils.html
  Perils and Princesses/Perils.png
  Perils and Princesses/sheet.json
  Perils and Princesses/translation.json
Labels: approved yaml change

#14344 [NEW SHEET] NIGHTS IN THE NEIGHBORHOOD (OFFICIAL)
  Nights in the Neighborhood/IMAGES/CRANEO_1_GATO.png
  Nights in the Neighborhood/IMAGES/CRANEO_2_MAPACHE.png
  Nights in the Neighborhood/IMAGES/CRANEO_3_ZARIGUEYA.png
  Nights in the Neighborhood/IMAGES/CRANEO_4_PERRO.png
  Nights in the Neighborhood/IMAGES/CRANEO_5_RATA.png
  Nights in the Neighborhood/IMAGES/CRANEO_6_LECHUZA.png
  Nights in the Neighborhood/IMAGES/NITN_DADOS_30x42px.png
  Nights in the Neighborhood/IMAGES/NITN_EXPAND_ENGLISH.png
  Nights in the Neighborhood/IMAGES/NITN_EXPAND_SPANISH.png
  Nights in the Neighborhood/IMAGES/NITN_FONDO_BACK_EN_860px_A1.jpg
  Nights in the Neighborhood/IMAGES/NITN_FONDO_BACK_ES_860px_A1.jpg
  Nights in the Neighborhood/IMAGES/NITN_FONDO_COMBAT_EN_860px_A2.jpg
  Nights in the Neighborhood/IMAGES/NITN_FONDO_COMBAT_ES_860px_A7.jpg
  Nights in the Neighborhood/IMAGES/NITN_FONDO_FRONT_EN_860px_A3.jpg
  Nights in the Neighborhood/IMAGES/NITN_FONDO_FRONT_ES_860px_A3.jpg
  Nights in the Neighborhood/IMAGES/TEMPLATE_BUTTON_MENU_NITN_A1_220px.jpg
  Nights in the Neighborhood/IMAGES/TEMPLATE_BUTTON_MENU_NITN_A2_220px.jpg
  Nights in the Neighborhood/IMAGES/TEMPLATE_BUTTON_MENU_NITN_A3_220px.jpg
  Nights in the Neighborhood/IMAGES/TEMPLATE_BUTTON_MENU_NITN_A4_220px.jpg
  Nights in the Neighborhood/IMAGES/TEMPLATE_BUTTON_MENU_NITN_A5_220px.jpg
  Nights in the Neighborhood/IMAGES/TEMPLATE_BUTTON_MENU_NITN_A6_220px.jpg
  Nights in the Neighborhood/IMAGES/TEMPLATE_BUTTON_MENU_NITN_A7_220px.jpg
  Nights in the Neighborhood/IMAGES/TEMPLATE_FONDO_NITN_A1_600px.png
  Nights in the Neighborhood/IMAGES/TEMPLATE_FONDO_NITN_A2_600px.png
  Nights in the Neighborhood/IMAGES/TEMPLATE_FONDO_NITN_A3_600px.png
  Nights in the Neighborhood/IMAGES/buho.png
  Nights in the Neighborhood/IMAGES/gato.png
  Nights in the Neighborhood/IMAGES/mapache.png
  Nights in the Neighborhood/IMAGES/otro.png
  Nights in the Neighborhood/IMAGES/perro.png
  Nights in the Neighborhood/IMAGES/rata.png
  Nights in the Neighborhood/IMAGES/zarigueya.png
  Nights in the Neighborhood/README.md
  Nights in the Neighborhood/nitn.css
  Nights in the Neighborhood/nitn.html
  Nights in the Neighborhood/nitn.png
  Nights in the Neighborhood/sheet.json
Labels: awaiting verification

#14371 [Lyrian Chronicles] New sheet to be added. Images will use roll20 github url by next update.
  LyrianChronicles/Assets/AttibuteVal.png
  LyrianChronicles/Assets/AttributeLabel.png
  LyrianChronicles/Assets/AttributeLabel2.png
  LyrianChronicles/Assets/LyrianBottomStamp.png
  LyrianChronicles/Assets/LyrianChroniclesBanner.png
  LyrianChronicles/Assets/LyrianContainer.png
  LyrianChronicles/Assets/LyrianContainer2.png
  LyrianChronicles/Assets/LyrianOuterBorder.png
  LyrianChronicles/Assets/diamond2.png
  LyrianChronicles/Assets/sheet-box-border.png
  LyrianChronicles/LyrianChronicles.css
  LyrianChronicles/LyrianChronicles.html
  LyrianChronicles/LyrianChronicles.png
  LyrianChronicles/sheet.json
Labels: awaiting verification
